### ISSUE TITLE
crash in beta 1.3

### ISSUE THREAD

**Issue by falong8** [amatt13/PostMortemPossession#1]
the game crash in the beta 1.3.0 with this mod. I hope you update it because this is the most useful mod that exists

**Comment by amatt13** [comment]
The mod fails in Beta as the have changed the API for accessing the MissionBehaviours in tournaments. 
I will fix the issue when the beta branch gets merged with the release/master branch.

**Comment by amatt13** [comment]
I have made a fix that works on my machine.
Can anyone test and see if this has reolved the issue for them as well?

I wont update Nexusmod before someone else has given me the 👍 
(b90e677c332e7619a56310e28b54771bfdf8ef49)

**Comment by falong8** [comment]
I don't know how implement that code but keep waiting for nexus's post

**Comment by amatt13** [comment]
The update was tested by a friendly user on NexusMods.

Confirmed to work with 1.3 and the 1.4 Beta branch
