### ISSUE TITLE
Crash on startup on 1.3.1

### ISSUE THREAD

**Issue by cvaylen** [amatt13/PostMortemPossession#2]
Game crashes on start with no other mods installed on game version 1.3.1 and mod 1.1.0.

**Comment by amatt13** [comment]
Do you have a stacktrace?
I'm currently on the Beta branch, so I will have to switch back to normal to test.

I will update when I know more.

**Comment by cvaylen** [comment]
I only have the crash dump.
[2020-05-13_14.22.12.zip](https://github.com/amatt13/PostMortemPossession/files/4622476/2020-05-13_14.22.12.zip)

**Comment by amatt13** [comment]
I cannot reproduce the problem.

How did you installed the mod?
Did you download it from the nexus, or did you clone this repo?

**Comment by cvaylen** [comment]
Downloaded from Nexus and installed in Vortex

**Comment by amatt13** [comment]
Can you confirm that you have downloaded the latest version? (1.1.0)
Have you manually unblocked the two .dll files?

**Comment by cvaylen** [comment]
After clearing everything else, Vortex consistently downloads a version whose SubModule.xml says Version value=1.0.1. No issue when I install it manually, bizarre.

**Comment by amatt13** [comment]
I'm happy that it is working for you :)
